params:  
  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
          # scale: 0.02
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [512, 256, 128]
      activation: elu
      d2rl: False

      initializer:
        name: default
      regularizer:
        name: None #'l2_regularizer'
        #scale: 0.001
  load_checkpoint: True # flag which sets whether to load the checkpoint
  load_path: /mnt/data/pyCharm-project/Reinforcement_Learning/RL_assembly/dexteroushandenvs/runs/Ur5eAssembly_27-14-41-16/nn/last_Ur5eAssembly_ep_8300_rew_6942.613.pth # path to the checkpoint to load


  config:
    ppo: True
    mixed_precision: False
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    reward_shaper:
      scale_value: 1
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95

    learning_rate: 5e-4
    lr_schedule: adaptive
    schedule_type: standard
    kl_threshold: 0.008
    score_to_win: 10000
    max_epochs: 100000
    save_frequency: 100
    save_best_after: 200
    print_stats: True
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 8
    minibatch_size: 32
    mini_epochs: 5
    critic_coef: 4
    clip_value: True
    seq_len: 4
    bounds_loss_coef: 0.0001
    name: allegro
    env_name: openai_gym
    env_config:
      seed: 42


    # 
    # score_to_win: 100000

    # grad_norm: 1
    # entropy_coef: 0.0
    # 
    # 
    # 
    # clip_value: True
    # num_agent: 1
    # 
    # minibatch_size: 64
    # 
    # critic_coef: 1
    # lr_schedule:  adaptive
    # kl_threshold: 0.016

    # 
    # 
    # games_to_track: 8
    
    # # normalize_input: False
    # seq_length: 4
    # bounds_loss_coef: 0.001


    player:
      #render: True
      deterministic: True
      max_steps: 100000000
      games_num: 100000000
      print_stats: True

    # central_value_config:
    #   minibatch_size: 32
    #   mini_epochs: 5
    #   learning_rate: 5e-4
    #   lr_schedule: adaptive
    #   schedule_type: standard
    #   kl_threshold: 0.016
    #   clip_value: True
    #   normalize_input: True
    #   truncate_grads: True

    #   network:
    #     name: actor_critic
    #     central_value: True
    #     mlp:
    #       units: [512, 256, 128]
    #       activation: elu
    #       d2rl: False
    #       initializer:
    #         name: default
    #       regularizer:
    #         name: None


