params:  
  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: True
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
          scale: 0.02
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [512, 256, 128]
      activation: elu
      d2rl: False
      
      initializer:
        name: default
      regularizer:
        name: None #'l2_regularizer'
        #scale: 0.001

  load_checkpoint: True
  load_path: './runs/AllegroHandLego_25-12-05-07/nn/last_AllegroHandLego_ep_3200_rew_0.10256375.pth  seed 22'
  # load_checkpoint: False
  # load_path: path

  config:
    reward_shaper:
      scale_value: 1
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95

    learning_rate: 3e-4
    name: allegro
    score_to_win: 100000

    grad_norm: 1
    entropy_coef: 0.0
    truncate_grads: True
    env_name: openai_gym
    e_clip: 0.2
    clip_value: True
    num_agent: 1
    horizon_length: 8
    minibatch_size: 32
    mini_epochs: 5
    critic_coef: 1
    lr_schedule:  adaptive
    kl_threshold: 0.016

    max_epochs: 51040
    save_frequency: 200
    save_best_after: 1000
    games_to_track: 8
    
    normalize_input: False
    seq_length: 4
    bounds_loss_coef: 0.001
    env_config:
      seed: 42

    player:
      #render: True
      deterministic: True
      max_steps: 1000000
      games_num: 1000000
      print_stats: False

    central_value_config:
      minibatch_size: 64
      mini_epochs: 5
      learning_rate: 5e-4
      lr_schedule: adaptive
      schedule_type: standard
      kl_threshold: 0.016
      clip_value: True
      normalize_input: True
      truncate_grads: True

      network:
        name: actor_critic
        central_value: True
        mlp:
          units: [512, 256, 128]
          activation: elu
          d2rl: False
          initializer:
            name: default
          regularizer:
            name: None


